# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lifted Logic Guidelines
email: info@liftedlogic.com
description: > # this means to ignore newlines until "baseurl:"
  The official Lifted Logic code guidelines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liftedlogic.com" # the base hostname & protocol for your site
twitter_username: liftedlogic
github_username:  liftedlogic

# Build settings
markdown: kramdown
